spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/filmRecommendService/db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console.enabled: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    database-change-log-lock-table: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE